baseURL = 'https://kavindu-udara.github.io/me/'
languageCode = 'en-us'
title = 'Kavindu Udara'
theme = 'archie'
relativeURLs = false
canonifyURLs = true

[params]
mode = "toggle"  # color-mode → light,dark,toggle, or auto
useCDN = false  # don't use CDNs for fonts and icons, instead serve them locally.
mathjax = true  # enable MathJax support
katex = true  # enable KaTeX support

# Main Menu Items

[[menu.main]]
name = "home"
url = "/"
weight = 1

[[menu.main]]
name = "blog"
url = "/posts"
weight = 2

[[menu.main]]
name = "github"
url = "https://github.com/kavindu-udara"
weight = 3

[[menu.main]]
name = "twitter"
url = "https://x.com/udarakavindu99"
weight = 4

[[menu.main]]
name = "linkedin"
url = "https://www.linkedin.com/in/kavindu-udara-sampath-karunasinghe"
weight = 5
